name: Build Windows

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build packages
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Download ANTs
      uses: robinraju/release-downloader@main
      with:
        repository: "raidionics/Raidionics-dependencies"
        latest: true
        fileName: "ANTsX-v2.4.3_windows.zip"
        out-file-path: "downloads"

    - name: Extract ANTs
      run: |
        cd ${{github.workspace}}/downloads/
        mkdir ${{github.workspace}}/ANTs/install
        tar -xf ANTsX*.zip -C ${{github.workspace}}/ANTs/install/

    - name: Collect submodules
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib==3.3.4
        pip install -e git+https://github.com/dbouget/raidionics_rads_lib.git@master#egg=raidionicsrads
        pip install -r assets/requirements.txt

    - name: Build software
      run: |              
        pip install pyinstaller
        mkdir tmp_dependencies
        pyinstaller --noconfirm --clean assets/main.spec

    - name: Make installer
      run: |
        makensis.exe assets/Raidionics.nsi
        cp -r assets/Raidionics-1.2.0-win.exe dist/Raidionics-1.2.0-win.exe

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: ${{github.workspace}}/dist/Raidionics-*
        if-no-files-found: error
